// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"modbus-emulator/conf"

	"github.com/swaggo/swag"
)

const docTemplate = `{
  "swagger": "2.0",
  "info": {
    "description": "HTTP API for utility management",
    "title": "HTTP-server for \"Modbus emulator\"",
    "version": "1.1.0"
  },
  "basePath": "/modbus-emulator",
  "schemes": [
    "http"
  ],
  "paths": {
    "/settings": {
      "get": {
        "tags": [
          "Settings"
        ],
        "description": "Get list of settings for all working servers",
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "settings": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Server"
                  }
                },
                "id": {
                  "type": "integer"
                }
              }
            }
          }
        }
      }
    },
    "/settings/{server}": {
      "get": {
        "tags": [
          "Settings"
        ],
        "description": "Get settings for working server",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "server",
            "in": "path",
            "required": true,
            "type": "integer"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Server"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Server": {
      "type": "object",
      "properties": {
        "dump_socket": {
          "type": "string"
        },
        "real_socket": {
          "type": "string"
        },
        "protocol": {
          "type": "string"
        },
        "one_time_emulation": {
          "type": "boolean"
        },
        "start_time": {
          "type": "string"
        },
        "end_time": {
          "type": "string"
        },
        "current_time": {
          "type": "string"
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.1.0",
	Host:             conf.ServerHTTPServesocket,
	BasePath:         "/modbus-emulator",
	Schemes:          []string{},
	Title:            "HTTP-server for \"Modbus emulator\"",
	Description:      "HTTP API for utility management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
